version: "3"

services:
  app:
    build: .
    container_name: clean-ddd-nestjs-app
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000

  db:
    image: mysql:8.0.30-debian
    container_name: clean-ddd-nestjs-db
    profiles:
      - dev
    environment:
      - MYSQL_DATABASE=clean-ddd-nestjs
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined

  db_test:
    image: mysql:8.0.30-debian
    container_name: clean-ddd-nestjs-db-test
    environment:
      - MYSQL_DATABASE=clean-ddd-nestjs_test
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
